project_id = "hrpnufesbjmaaiqgjwtn"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.hubla-webhook]
    verify_jwt = false
  [functions.sommelier-chat]
    verify_jwt = false
  [functions.panda-proxy]
    verify_jwt = false
  [functions.panda-webhook]
    verify_jwt = false
