import type { MockWine } from "./WineCard";

export const mockWines: MockWine[] = [
  {
    id: "mock-1",
    name: "Catena Zapata Malbec",
    producer: "Bodega Catena Zapata",
    vintage: 2021,
    grape: "Malbec",
    type: "Tinto",
    country: "Argentina",
    importer: "Grand Cru",
    price_range: "R$ 150–200",
    image_url: "https://images.vivino.com/thumbs/ApThIPGaTGIFCdO2WJkDkQ_375x500.jpg",
    tasting_notes: "Malbec clássico de altitude com taninos aveludados, notas de ameixa preta e um toque de chocolate. Excelente custo-benefício para quem quer conhecer o terroir de Mendoza.",
    seal_wine_type: "Encorpado",
    seal_drinker_type: "Intermediário",
  },
  {
    id: "mock-2",
    name: "Cloudy Bay Sauvignon Blanc",
    producer: "Cloudy Bay",
    vintage: 2023,
    grape: "Sauvignon Blanc",
    type: "Branco",
    country: "Nova Zelândia",
    importer: "World Wine",
    price_range: "R$ 180–250",
    image_url: "https://images.vivino.com/thumbs/3gQVlmYATruyxZLSZArujA_375x500.jpg",
    tasting_notes: "Aromático e vibrante, com notas de maracujá e grama cortada. Acidez refrescante que pede frutos do mar. Um branco para converter quem só bebe tinto.",
    seal_wine_type: "Frutado",
    seal_drinker_type: "Iniciante",
  },
  {
    id: "mock-3",
    name: "Penfolds Bin 389",
    producer: "Penfolds",
    vintage: 2020,
    grape: "Cabernet Sauvignon / Shiraz",
    type: "Tinto",
    country: "Austrália",
    importer: "Decanter",
    price_range: "R$ 350–450",
    image_url: "https://images.vivino.com/thumbs/4RQAgsvMSe1FJEPjkRkarg_375x500.jpg",
    tasting_notes: "O 'Baby Grange'. Blend poderoso com camadas de cassis, cedro e especiarias. Vinho de guarda que já entrega muito jovem. Para quem quer entender a grandeza australiana.",
    seal_wine_type: "Encorpado",
    seal_drinker_type: "Avançado",
  },
  {
    id: "mock-4",
    name: "Marqués de Murrieta Reserva",
    producer: "Marqués de Murrieta",
    vintage: 2019,
    grape: "Tempranillo",
    type: "Tinto",
    country: "Espanha",
    importer: "Mistral",
    price_range: "R$ 200–280",
    image_url: "https://images.vivino.com/thumbs/jtv1DVz9S12msl9gvYHi-g_375x500.jpg",
    tasting_notes: "Rioja elegante e clássico. Frutas vermelhas maduras, baunilha e um final longo com notas de couro. Harmoniza perfeitamente com cordeiro ou queijos curados.",
    seal_wine_type: "Médio",
    seal_drinker_type: "Intermediário",
  },
  {
    id: "mock-5",
    name: "Whispering Angel Rosé",
    producer: "Château d'Esclans",
    vintage: 2023,
    grape: "Grenache / Cinsault",
    type: "Rosé",
    country: "França",
    importer: "Expand",
    price_range: "R$ 180–230",
    image_url: "https://images.vivino.com/thumbs/vALbrMxSwQTKh4FJP7QLOQ_375x500.jpg",
    tasting_notes: "O rosé mais famoso do mundo não decepciona. Pálido, delicado, com notas de morango e flor de cerejeira. Perfeito para o verão brasileiro.",
    seal_wine_type: "Leve",
    seal_drinker_type: "Iniciante",
  },
  {
    id: "mock-6",
    name: "Brunello di Montalcino Banfi",
    producer: "Castello Banfi",
    vintage: 2018,
    grape: "Sangiovese",
    type: "Tinto",
    country: "Itália",
    importer: "Grand Cru",
    price_range: "R$ 400–550",
    image_url: "https://images.vivino.com/thumbs/K2UOIq2pRVKs-5D0ndPJSQ_375x500.jpg",
    tasting_notes: "Brunello majestoso com notas de cereja seca, tabaco e terra. Taninos firmes mas polidos. Um vinho para momentos especiais que recompensa cada gole.",
    seal_wine_type: "Encorpado",
    seal_drinker_type: "Avançado",
  },
];
