import type { MockWine } from "./WineCard";
import catenaMalbec from "@/assets/wines/catena-zapata-malbec.jpg";
import cloudyBay from "@/assets/wines/cloudy-bay-sauvignon-blanc.jpg";
import penfoldsBin389 from "@/assets/wines/penfolds-bin-389.jpg";
import marquesMurrieta from "@/assets/wines/marques-murrieta-reserva.jpg";
import whisperingAngel from "@/assets/wines/whispering-angel-rose.jpg";
import brunelloBanfi from "@/assets/wines/brunello-banfi.jpg";

export const mockWines: MockWine[] = [
  {
    id: "mock-1",
    name: "Catena Zapata Malbec",
    producer: "Bodega Catena Zapata",
    vintage: 2021,
    grape: "Malbec",
    type: "Tinto",
    country: "Argentina",
    importer: "Grand Cru",
    price: "R$ 179,90",
    image_url: catenaMalbec,
    tasting_notes: "Malbec clássico de altitude com taninos aveludados, notas de ameixa preta e um toque de chocolate. Excelente custo-benefício para quem quer conhecer o terroir de Mendoza.",
    seal_wine_type: "batalha",
    seal_drinker_type: "curioso",
  },
  {
    id: "mock-2",
    name: "Cloudy Bay Sauvignon Blanc",
    producer: "Cloudy Bay",
    vintage: 2023,
    grape: "Sauvignon Blanc",
    type: "Branco",
    country: "Nova Zelândia",
    importer: "World Wine",
    price: "R$ 219,90",
    image_url: cloudyBay,
    tasting_notes: "Aromático e vibrante, com notas de maracujá e grama cortada. Acidez refrescante que pede frutos do mar. Um branco para converter quem só bebe tinto.",
    seal_wine_type: "refrescante",
    seal_drinker_type: "natureba",
  },
  {
    id: "mock-3",
    name: "Penfolds Bin 389",
    producer: "Penfolds",
    vintage: 2020,
    grape: "Cabernet Sauvignon / Shiraz",
    type: "Tinto",
    country: "Austrália",
    importer: "Decanter",
    price: "R$ 399,90",
    image_url: penfoldsBin389,
    tasting_notes: "O 'Baby Grange'. Blend poderoso com camadas de cassis, cedro e especiarias. Vinho de guarda que já entrega muito jovem. Para quem quer entender a grandeza australiana.",
    seal_wine_type: "pedigree",
    seal_drinker_type: "nerd",
  },
  {
    id: "mock-4",
    name: "Marqués de Murrieta Reserva",
    producer: "Marqués de Murrieta",
    vintage: 2019,
    grape: "Tempranillo",
    type: "Tinto",
    country: "Espanha",
    importer: "Mistral",
    price: "R$ 249,90",
    image_url: marquesMurrieta,
    tasting_notes: "Rioja elegante e clássico. Frutas vermelhas maduras, baunilha e um final longo com notas de couro. Harmoniza perfeitamente com cordeiro ou queijos curados.",
    seal_wine_type: "contemplativo",
    seal_drinker_type: "classico",
  },
  {
    id: "mock-5",
    name: "Whispering Angel Rosé",
    producer: "Château d'Esclans",
    vintage: 2023,
    grape: "Grenache / Cinsault",
    type: "Rosé",
    country: "França",
    importer: "Expand",
    price: "R$ 199,90",
    image_url: whisperingAngel,
    tasting_notes: "O rosé mais famoso do mundo não decepciona. Pálido, delicado, com notas de morango e flor de cerejeira. Perfeito para o verão brasileiro.",
    seal_wine_type: "refrescante",
    seal_drinker_type: "curioso",
  },
  {
    id: "mock-6",
    name: "Brunello di Montalcino Banfi",
    producer: "Castello Banfi",
    vintage: 2018,
    grape: "Sangiovese",
    type: "Tinto",
    country: "Itália",
    importer: "Grand Cru",
    price: "R$ 489,90",
    image_url: brunelloBanfi,
    tasting_notes: "Brunello majestoso com notas de cereja seca, tabaco e terra. Taninos firmes mas polidos. Um vinho para momentos especiais que recompensa cada gole.",
    seal_wine_type: "pedigree",
    seal_drinker_type: "nerd",
  },
];
