name: Deploy iOS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          echo "Instalando dependências com flags legacy-peer-deps e force..."
          npm install --legacy-peer-deps --force

      - name: Build project
        run: |
          echo "Executando build do projeto..."
          npm run build

      - name: Add iOS platform
        run: |
          echo "Adicionando plataforma iOS com Capacitor..."
          run: npx cap sync ios
          echo "Plataforma iOS adicionada com sucesso."
